### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by gdkrmr** [jlmelville/sneer#1]
Nice package, are you planning to submit this to CRAN?

**Comment by jlmelville** [comment]
Thanks. I plan to submit this to CRAN at some point, but I don't have a specific time frame in mind, mainly because I admittedly haven't researched to see what extra checks it would need to pass in addition to the 'Check Package' settings in RStudio (which it currently does pass).

I will start thinking about it more seriously now though.

**Comment by gdkrmr** [comment]
that would be great!

**Comment by jlmelville** [comment]
Going to close this (as wontfix) for now, because I don't want to get anyone's hopes up. Having looked at the CRAN policy, I'm unlikely to submit sneer. One of the problems would be not having the tests run for too long, and currently the tests for sneer take about ten minutes to finish on my quad core Sandy Bridge laptop. I don't plan to rewrite them any time soon.

FWIW, in addition to keeping the tests passing, I do endeavor to ensure that the automated Check Package tests always pass without notes, errors or warnings.

Sorry to disappoint.

**Comment by gdkrmr** [comment]
no problem, I can install the package from github anyways.

**Comment by gdkrmr** [comment]
I just checked with latest master, your tests run fast now.
